import PropTypes from "prop-types";
import "./globals.css";
import Sidebar from "@/frontend/components/sideBar/SideBar";
import AuthProvider from "@/utils/AuthProvider";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/utils/ReduxProvider";
import { ThemeProvider } from "@/frontend/contexts/ThemeContext";
import Header from "@/frontend/components/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <title>Meu Site</title>
        <meta name="description" content="Descrição do meu site" />
      </head>
      <body className="font-sans bg-light-background text-light-text dark:bg-dark-background dark:text-dark-text">
        <ThemeProvider>
          <AuthProvider>
            <Toaster position="top-right" />
            <Header />
            <div>
              <Sidebar />
              <main className="p-0 pt-[5.5rem] md:pl-[6rem] md:pb-[2rem] md:pr-[1rem]">
                <ReduxProvider>{children}</ReduxProvider>
              </main>
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
