import PropTypes from "prop-types";
import "./globals.css";

import Sidebar from "@/frontend/components/sideBar/SideBar";

import AuthProvider from "@/utils/AuthProvider";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/utils/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <title>Meu Site</title>
        <meta name="description" content="Descrição do meu site" />
      </head>
      <body className="font-sans bg-gradient-light dark:bg-gradient-dark text-light-text dark:text-dark-text">
        <AuthProvider>
          <Toaster position="top-right" />
          <div className="flex min-h-screen">
            <Sidebar />
            <main>
              <ReduxProvider>{children}</ReduxProvider>
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
